// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI6_rKk2HcjJGpR5_fMPFOUDv8uBAZA3w',
    appId: '1:311063674206:android:99c4755734fab0c5e063cf',
    messagingSenderId: '311063674206',
    projectId: 'synergy-f634e',
    storageBucket: 'synergy-f634e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU9fVBoFLfO1DA9-MxQWU013HZF1n2qmw',
    appId: '1:311063674206:ios:45c2c2247514596be063cf',
    messagingSenderId: '311063674206',
    projectId: 'synergy-f634e',
    storageBucket: 'synergy-f634e.appspot.com',
    iosBundleId: 'com.example.synergy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU9fVBoFLfO1DA9-MxQWU013HZF1n2qmw',
    appId: '1:311063674206:ios:45c2c2247514596be063cf',
    messagingSenderId: '311063674206',
    projectId: 'synergy-f634e',
    storageBucket: 'synergy-f634e.appspot.com',
    iosBundleId: 'com.example.synergy',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXmmNZuqy3XPZ5lr-Ch6Tdanctws7DoJw',
    appId: '1:311063674206:web:60922c2613a065a5e063cf',
    messagingSenderId: '311063674206',
    projectId: 'synergy-f634e',
    authDomain: 'synergy-f634e.firebaseapp.com',
    storageBucket: 'synergy-f634e.appspot.com',
    measurementId: 'G-NFNDLGQX2X',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXmmNZuqy3XPZ5lr-Ch6Tdanctws7DoJw',
    appId: '1:311063674206:web:f9bae3d0c60e663be063cf',
    messagingSenderId: '311063674206',
    projectId: 'synergy-f634e',
    authDomain: 'synergy-f634e.firebaseapp.com',
    storageBucket: 'synergy-f634e.appspot.com',
    measurementId: 'G-B45M2LESSS',
  );

}